MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/cv/.torch/models/resnet18-5c106cde.pth"
  BACKBONE:
    CONV_BODY: "R-18-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 21
  RESNETS:
    USE_BOTTLENECK: False
    TRANS_FUNC: "ResBlockWithFixedBatchNorm"
DATASETS:
  TRAIN: ("voc_0712_trainval", )
  TEST: ("voc_0712_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, )
  MAX_ITER: 70000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 2000
TEST:
  IMS_PER_BATCH: 1
